inherit_from: .rubocop_todo.yml

require:
  rubocop-i18n

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'lib/**/*.rb'
    - 'ext/**/*.rb'
  Exclude:
    - '**/*.erb'
    - 'acceptance/**/*'
    - 'spec/**/*'
    - 'tasks/**/*'
    - 'ext/suse/puppet.spec'
    - 'lib/puppet/vendor/**/*'
    - 'lib/puppet/pops/parser/eparser.rb'

# puppet uses symbol booleans in types and providers to work around long standing
# bugs when trying to manage falsey pararameters and properties
Lint/BooleanSymbol:
  Enabled: true
  Exclude:
    - 'lib/puppet/type.rb'
    - 'lib/puppet/type/**/*.rb'
    - 'lib/puppet/provider/**/*.rb'
    - 'lib/puppet/reference/providers.rb'
    - 'lib/puppet/parameter/value.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'lib/puppet/ffi/windows/structs.rb'
    - 'lib/puppet/pops/validation/checker4_0.rb'
    - 'lib/puppet/pops/validation/validator_factory_4_0.rb'
    - 'lib/puppet/util/windows/root_certs.rb'
    - 'lib/puppet/util/windows/security.rb'
    - 'lib/puppet/util/windows/user.rb'

Naming/ConstantName:
  Exclude:
    - 'lib/puppet/graph/relationship_graph.rb'
    - 'lib/puppet/indirector/hiera.rb'
    - 'lib/puppet/provider/package/sun.rb'
    - 'lib/puppet/resource/type.rb'
    - 'lib/puppet/type/schedule.rb'
    - 'lib/puppet/type/tidy.rb'
    - 'lib/puppet/util.rb'
    - 'lib/puppet/util/colors.rb'
    - 'lib/puppet/util/execution.rb'
    - 'lib/puppet/util/symbolic_file_mode.rb'
    - 'lib/puppet/util/tagging.rb'
    - 'lib/puppet/util/windows/adsi.rb'
    - 'lib/puppet/util/windows/sid.rb'
    - 'lib/puppet/util/yaml.rb'

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
